version: "3"

services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      - NODE_ID=1
      - PEER_IDS=2,3,4,5
    ports:
      - "50051:50051"
    networks:
      - raft_network

  node2:
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      - NODE_ID=2
      - PEER_IDS=1,3,4,5
    ports:
      - "50052:50051"
    networks:
      - raft_network

  node3:
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      - NODE_ID=3
      - PEER_IDS=1,2,4,5
    ports:
      - "50053:50051"
    networks:
      - raft_network

  node4:
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      - NODE_ID=4
      - PEER_IDS=1,2,3,5
    ports:
      - "50054:50051"
    networks:
      - raft_network

  node5:
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      - NODE_ID=5
      - PEER_IDS=1,2,3,4
    ports:
      - "50055:50051"
    networks:
      - raft_network

  node6:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ID=6
      - PEER_IDS=
    ports:
      - "50056:50051"
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
    networks:
      - raft_network

networks:
  raft_network:
    driver: bridge
